"""Wound wordings by body area, severity and kind — generated, do not edit.

Source: https://elanthipedia.play.net/Damage (tools/wound_tables.py regenerates this file).
Rows are (area, level, kind, phrase); levels 1-8 are insignificant,
negligible, minor, harmful, damaging, severe, devastating, useless;
kinds are external, scar, internal, internal_scar. Placeholders
"[right/left]" / "[left/right]" and "[hand/arm/leg/tail]" are the
wiki's; client/wounds.py expands them.
"""

# fmt: off
ROWS = (
    ("head", 1, "external", "faint scuffing to the head"),
    ("head", 1, "scar", "some faint scars along the head"),
    ("head", 1, "external", "minor abrasions to the head"),
    ("head", 1, "scar", "a few nearly invisible scars along the head"),
    ("head", 2, "external", "tiny scratches to the head"),
    ("head", 2, "scar", "some tiny scars across the head"),
    ("head", 3, "external", "cuts and bruises about the head"),
    ("head", 3, "scar", "minor scars about the head"),
    ("head", 3, "internal", "a bruised head"),
    ("head", 3, "internal_scar", "an occasional twitch on the forehead"),
    ("head", 4, "external", "some moderately deep cuts about the head"),
    ("head", 4, "scar", "severe scarring about the head"),
    ("head", 4, "internal", "a deeply bruised head"),
    ("head", 4, "internal_scar", "an occasional twitch on the forehead"),
    ("head", 5, "external", "some deep slashes and cuts about the head"),
    ("head", 5, "scar", "severe scarring and ugly gashes about the head"),
    ("head", 5, "internal", "major swelling and bruising around the head"),
    ("head", 5, "internal_scar", "an occasional twitch on the forehead"),
    ("head", 6, "external", "a cracked skull with deep slashes"),
    ("head", 6, "scar", "missing chunks out of the head"),
    ("head", 6, "internal", "a ghastly bloated head with bleeding from the ears"),
    ("head", 6, "internal_scar", "a confused look with sporadic twitching of the forehead"),
    ("head", 7, "external", "a crushed skull with horrendous wounds"),
    ("head", 7, "scar", "a mangled and malformed head"),
    ("head", 7, "internal", "a ghastly bloated head with bleeding from the ears"),
    ("head", 7, "internal_scar", "a confused look with sporadic twitching of the forehead"),
    ("head", 8, "external", "A pulpy stump for a head"),
    ("head", 8, "scar", "a stump for a head"),
    ("head", 8, "internal", "a grotesquely bloated head with bleeding from the eyes and ears"),
    ("head", 8, "internal_scar", "a blank stare"),
    ("eye", 1, "external", "faint scuffing to the [right/left] eye"),
    ("eye", 1, "scar", "some faint scars along the [right/left] eye"),
    ("eye", 1, "external", "minor abrasions to the [right/left] eye"),
    ("eye", 1, "scar", "a few nearly invisible scars along the [right/left] eye"),
    ("eye", 2, "external", "light scratches to the [right/left] eye"),
    ("eye", 2, "scar", "some tiny scars along the [right/left] eye"),
    ("eye", 3, "external", "a black and blue [right/left] eye"),
    ("eye", 3, "scar", "minor scars across the [right/left] eye"),
    ("eye", 3, "internal", "some minor swelling and bruising around the [right/left] eye"),
    ("eye", 3, "internal_scar", "an occasional twitching in the [right/left] eye"),
    ("eye", 4, "external", "a bruised and swollen [right/left] eye"),
    ("eye", 4, "scar", "severe scarring across the [right/left] eye"),
    ("eye", 4, "internal", "a severely swollen and bruised [right/left] eye"),
    ("eye", 4, "internal_scar", "a constant twitching in the [right/left] eye"),
    ("eye", 5, "external", "a bruised, swollen and bleeding [right/left] eye"),
    ("eye", 5, "scar", "deeply scarred gashes across the [right/left] eye"),
    ("eye", 5, "internal", "a severely swollen, bruised and crossed [right/left] eye"),
    ("eye", 5, "internal_scar", "a constant twitching in the [right/left] eye"),
    ("eye", 6, "external", "a bruised, swollen and slashed [right/left] eye"),
    ("eye", 6, "scar", "a punctured and shriveled [right/left] eye"),
    ("eye", 6, "internal", "a severely swollen, bruised and cloudy [right/left] eye"),
    ("eye", 6, "internal_scar", "a clouded [right/left] eye"),
    ("eye", 7, "external", "a bruised, swollen and shattered [right/left] eye"),
    ("eye", 7, "scar", "a painfully mangled and malformed [right/left] eye in a shattered eye socket"),
    ("eye", 7, "internal", "a severely swollen, bruised and blind [right/left] eye"),
    ("eye", 7, "internal_scar", "a completely clouded [right/left] eye"),
    ("eye", 8, "external", "a pulpy cavity for a [right/left] eye"),
    ("eye", 8, "scar", "an empty [right/left] eye socket overgrown with bits of odd shaped flesh"),
    ("eye", 8, "internal", "a severely swollen, bruised and blind [right/left] eye"),
    ("eye", 8, "internal_scar", "a blind [right/left] eye"),
    ("neck", 1, "external", "faint scuffing to the neck"),
    ("neck", 1, "scar", "some faint scars along the neck"),
    ("neck", 1, "external", "minor abrasions to the neck"),
    ("neck", 1, "scar", "a few nearly invisible scars along the neck"),
    ("neck", 2, "external", "tiny scratches to the neck"),
    ("neck", 2, "scar", "some tiny scars across the neck"),
    ("neck", 3, "external", "cuts and bruises about the neck"),
    ("neck", 3, "scar", "minor scarring along the neck"),
    ("neck", 3, "internal", "minor swelling and bruising around the neck"),
    ("neck", 3, "internal_scar", "an occasional twitching in the neck"),
    ("neck", 4, "external", "deep cuts across the neck"),
    ("neck", 4, "scar", "severe scarring along the neck"),
    ("neck", 4, "internal", "a severely swollen and deeply bruised neck"),
    ("neck", 4, "internal_scar", "a constant twitching in the neck"),
    ("neck", 5, "external", "deep slashes across the neck"),
    ("neck", 5, "scar", "severe scarring and ugly gashes about the neck"),
    ("neck", 5, "internal", "a severely swollen and deeply bruised neck"),
    ("neck", 5, "internal_scar", "a constant twitching in the neck"),
    ("neck", 6, "external", "gaping holes in the neck"),
    ("neck", 6, "scar", "severe scarring and ugly gashes about the neck"),
    ("neck", 6, "internal", "a severely swollen and deeply bruised neck with odd protrusions under the skin"),
    ("neck", 6, "internal_scar", "a partially paralyzed neck"),
    ("neck", 7, "external", "a shattered neck with gaping wounds"),
    ("neck", 7, "scar", "severely scarred, mangled and malformed neck"),
    ("neck", 7, "internal", "a severely swollen and deeply bruised neck with bones protruding out from the skin"),
    ("neck", 7, "internal_scar", "a severely paralyzed neck"),
    ("neck", 8, "external", "a completely useless neck with nearly all flesh and bone torn away"),
    ("neck", 8, "scar", "an ugly flesh stump for a neck with little left to support the head"),
    ("neck", 8, "internal", "a severely swollen and shattered neck which appears useless to hold up the head"),
    ("neck", 8, "internal_scar", "a completely paralyzed neck"),
    ("chest", 1, "external", "faint scuffing to the chest"),
    ("chest", 1, "scar", "some faint scars along the chest"),
    ("chest", 1, "external", "minor abrasions to the chest"),
    ("chest", 1, "scar", "a few nearly invisible scars along the chest"),
    ("chest", 2, "external", "some tiny scratches to the chest"),
    ("chest", 2, "scar", "some tiny scars across the chest"),
    ("chest", 3, "external", "cuts and bruises about the chest area"),
    ("chest", 3, "scar", "minor scarring along the chest area"),
    ("chest", 3, "internal", "minor swelling and bruising in the chest area"),
    ("chest", 3, "internal_scar", "an occasional twitching in the chest area"),
    ("chest", 4, "external", "deep cuts across the chest area"),
    ("chest", 4, "scar", "severe scarring along the chest area"),
    ("chest", 4, "internal", "a severely swollen and bruised chest area"),
    ("chest", 4, "internal_scar", "a constant twitching in the chest area"),
    ("chest", 5, "external", "deep slashes across the chest area"),
    ("chest", 5, "scar", "severe scarring and ugly gashes about the chest area"),
    ("chest", 5, "internal", "a severely swollen and bruised chest area"),
    ("chest", 5, "internal_scar", "a constant twitching in the chest area and difficulty breathing"),
    ("chest", 6, "external", "gaping holes in the chest area"),
    ("chest", 6, "scar", "severe scarring and chunks of flesh missing from the chest area"),
    ("chest", 6, "internal", "a severely swollen and deeply bruised chest area with odd protrusions under the skin"),
    ("chest", 6, "internal_scar", "a painful chest area and difficulty getting a breath without pain"),
    ("chest", 7, "external", "shattered chest area with gaping wounds"),
    ("chest", 7, "scar", "a severely scarred, mangled and malformed chest area"),
    ("chest", 7, "internal", "a severely swollen and deeply bruised chest area with ribs protruding out from the skin"),
    ("chest", 7, "internal_scar", "a severely painful chest area with significant problems breathing"),
    ("chest", 8, "external", "a completely destroyed chest with nearly all flesh and bone torn away revealing a gaping hole"),
    ("chest", 8, "scar", "a mostly non-existent chest filled with ugly chunks of scarred flesh"),
    ("chest", 8, "internal", "a severely swollen chest area with a shattered rib cage"),
    ("chest", 8, "internal_scar", "an extremely painful chest while gasping for breath in short shallow bursts"),
    ("abdomen", 1, "external", "faint scuffing to the abdomen"),
    ("abdomen", 1, "scar", "some faint scars along the abdomen"),
    ("abdomen", 1, "external", "minor abrasions to the abdomen"),
    ("abdomen", 1, "scar", "a few nearly invisible scars along the abdomen"),
    ("abdomen", 2, "external", "some tiny scratches to the abdomen"),
    ("abdomen", 2, "scar", "some tiny scars across the abdomen"),
    ("abdomen", 3, "external", "cuts and bruises about the abdomen"),
    ("abdomen", 3, "scar", "minor scarring along the abdomen"),
    ("abdomen", 3, "internal", "minor swelling and bruising in the abdomen"),
    ("abdomen", 3, "internal_scar", "an occasional twitching in the abdomen"),
    ("abdomen", 4, "external", "deep cuts across the abdomen"),
    ("abdomen", 4, "scar", "severe scarring along the abdomen"),
    ("abdomen", 4, "internal", "a severely swollen and bruised abdomen"),
    ("abdomen", 4, "internal_scar", "a constant twitching in the abdomen"),
    ("abdomen", 5, "external", "deep slashes across the abdomen"),
    ("abdomen", 5, "scar", "severe scarring and ugly gashes about the abdomen"),
    ("abdomen", 5, "internal", "a severely swollen and bruised abdomen"),
    ("abdomen", 5, "internal_scar", "a somewhat emaciated look"),
    ("abdomen", 6, "external", "gaping holes in the abdomen"),
    ("abdomen", 6, "scar", "severe scarring and chunks of flesh missing from the abdomen"),
    ("abdomen", 6, "internal", "a severely bloated and discolored abdomen with strange round lumps under the skin"),
    ("abdomen", 6, "internal_scar", "a definite greenish pallor and emaciated look"),
    ("abdomen", 7, "external", "an abdomen deeply gouged with gaping wounds"),
    ("abdomen", 7, "scar", "a severely scarred, mangled and malformed abdomen"),
    ("abdomen", 7, "internal", "a severely bloated and discolored abdomen with strange round lumps under the skin"),
    ("abdomen", 7, "internal_scar", "a severely yellow pallor and a look of starvation"),
    ("abdomen", 8, "external", "a completely destroyed abdomen with nearly all flesh and bone torn away revealing a gaping hole"),
    ("abdomen", 8, "scar", "a mostly non-existent abdomen filled with ugly chunks of scarred flesh"),
    ("abdomen", 8, "internal", "a severely bloated and discolored abdomen which appears oddly rearranged"),
    ("abdomen", 8, "internal_scar", "a death pallor and extreme loss of weight"),
    ("back", 1, "external", "faint scuffing to the back"),
    ("back", 1, "scar", "some faint scars along the back"),
    ("back", 1, "external", "minor abrasions to the back"),
    ("back", 1, "scar", "a few nearly invisible scars along the back"),
    ("back", 2, "external", "tiny scratches to the back"),
    ("back", 2, "scar", "some tiny scars across the back"),
    ("back", 3, "external", "cuts and bruises about the back"),
    ("back", 3, "scar", "minor scarring along the back"),
    ("back", 3, "internal", "minor swelling and bruising in the back"),
    ("back", 3, "internal_scar", "an occasional twitching in the back"),
    ("back", 4, "external", "deep cuts across the back"),
    ("back", 4, "scar", "severe scarring along the back"),
    ("back", 4, "internal", "a severely swollen and bruised back"),
    ("back", 4, "internal_scar", "a constant twitching in the back and difficulty moving in general"),
    ("back", 5, "external", "deep slashes across the back"),
    ("back", 5, "scar", "severe scarring and ugly gashes about the back"),
    ("back", 5, "internal", "a severely swollen and bruised back"),
    ("back", 5, "internal_scar", "a constant twitching in the back and difficulty moving in general"),
    ("back", 6, "external", "gaping holes in the back"),
    ("back", 6, "scar", "severe scarring and chunks of flesh missing from the back"),
    ("back", 6, "internal", "a severely swollen and deeply bruised back with odd protrusions under the skin"),
    ("back", 6, "internal_scar", "a painful back and difficulty moving without pain"),
    ("back", 7, "external", "a shattered back with gaping wounds"),
    ("back", 7, "scar", "severely scarred, mangled and malformed back"),
    ("back", 7, "internal", "a severely swollen and deeply bruised back with ribs or vertebrae protruding out from the skin"),
    ("back", 7, "internal_scar", "a severely painful back with significant problems moving"),
    ("back", 8, "external", "a completely destroyed back with nearly all flesh and bone torn away revealing a gaping hole"),
    ("back", 8, "scar", "a mostly non-existent back filled with ugly chunks of scarred flesh and rearranged bone"),
    ("back", 8, "internal", "a severely swollen back with a shattered spinal cord"),
    ("back", 8, "internal_scar", "an extremely painful and bizarrely twisted back making it nearly impossible to move"),
    ("limb", 1, "external", "faint scuffing to the [left/right] [hand/arm/leg/tail]"),
    ("limb", 1, "scar", "some faint scars along the [left/right] [hand/arm/leg/tail]"),
    ("limb", 1, "external", "minor abrasions to the [left/right] [hand/arm/leg/tail]"),
    ("limb", 1, "scar", "a few nearly invisible scars along the [left/right] [hand/arm/leg/tail]"),
    ("limb", 2, "external", "tiny scratches to the [left/right] [hand/arm/leg/tail]"),
    ("limb", 2, "scar", "some tiny scars across the [left/right] [hand/arm/leg/tail]"),
    ("limb", 3, "external", "cuts and bruises about the [left/right] [hand/arm/leg/tail]"),
    ("limb", 3, "scar", "minor scarring along the [left/right] [hand/arm/leg/tail]"),
    ("limb", 3, "internal", "minor swelling and bruising around the [left/right] [hand/arm/leg/tail]"),
    ("limb", 3, "internal_scar", "occasional twitching in the [left/right] [hand/arm/leg/tail]"),
    ("limb", 4, "external", "deep cuts across the [left/right] [hand/arm/leg/tail]"),
    ("limb", 4, "scar", "severe scarring along the [left/right] [hand/arm/leg/tail]"),
    ("limb", 4, "internal", "a severely swollen and deeply bruised [left/right] [hand/arm/leg/tail]"),
    ("limb", 4, "internal_scar", "a constant twitching in the [left/right] [hand/arm/leg/tail]"),
    ("limb", 5, "external", "deep slashes across the [left/right] [hand/arm/leg/tail]"),
    ("limb", 5, "scar", "severe scarring and ugly gashes about the [left/right] [hand/arm/leg/tail]"),
    ("limb", 5, "internal", "a severely swollen and deeply bruised [left/right] [hand/arm/leg/tail]"),
    ("limb", 5, "internal_scar", "a constant twitching in the [left/right] [hand/arm/leg/tail]"),
    ("limb", 6, "external", "a broken [left/right] [hand/arm/leg/tail] with gaping holes"),
    ("limb", 6, "scar", "severe scarring and chunks of flesh missing from the [left/right] [hand/arm/leg/tail]"),
    ("limb", 6, "internal", "a severely swollen and deeply bruised [left/right] [hand/arm/leg/tail] with odd protrusions under the skin"),
    ("limb", 6, "internal_scar", "a partially paralyzed [left/right] [hand/arm/leg/tail]"),
    ("limb", 7, "external", "a shattered [left/right] [hand/arm/leg/tail] with gaping wounds"),
    ("limb", 7, "scar", "a severely scarred, mangled and malformed [left/right] [hand/arm/leg/tail]"),
    ("limb", 7, "internal", "a severely swollen and deeply bruised [left/right] [hand/arm/leg/tail] with bones protruding out from the skin"),
    ("limb", 7, "internal_scar", "a severely paralyzed [left/right] [hand/arm/leg/tail]"),
    ("limb", 8, "external", "an ugly stump for a [left/right] [hand/arm/leg/tail]"),
    ("limb", 8, "scar", "an ugly flesh stump for a [left/right] [hand/arm/leg/tail]"),
    ("limb", 8, "internal", "a severely swollen and shattered [left/right] [hand/arm/leg/tail] which appears completely useless"),
    ("limb", 8, "internal_scar", "a completely paralyzed [left/right] [hand/arm/leg/tail]"),
    ("skin", 1, "external", "faint scuffing to the skin"),
    ("skin", 1, "scar", "some faint scars along the scars along the skin"),
    ("skin", 1, "external", "minor abrasions to the skin"),
    ("skin", 1, "scar", "a few nearly invisible scars along the skin"),
    ("skin", 2, "external", "tiny scratches to the skin"),
    ("skin", 2, "scar", "some tiny scars across the skin"),
    ("skin", 3, "external", "a small skin rash"),
    ("skin", 3, "scar", "loss of skin tone"),
    ("skin", 3, "internal", "some minor twitching"),
    ("skin", 3, "internal_scar", "slight difficulty moving your fingers and toes"),
    ("skin", 4, "external", "a large skin rash"),
    ("skin", 4, "scar", "minor skin discoloration"),
    ("skin", 4, "internal", "some severe twitching"),
    ("skin", 4, "internal_scar", "slight numbness in your arms and legs"),
    ("skin", 5, "external", "a body rash"),
    ("skin", 5, "scar", "severe skin discoloration"),
    ("skin", 5, "internal", "difficulty controlling actions"),
    ("skin", 5, "internal_scar", "numbness in your fingers and toes"),
    ("skin", 6, "external", "a painful, inflamed body rash"),
    ("skin", 6, "scar", "some shriveled and oddly folded skin"),
    ("skin", 6, "internal", "partial paralysis of the entire body"),
    ("skin", 6, "internal_scar", "numbness in your arms and legs"),
    ("skin", 7, "external", "boils and sores around the skin"),
    ("skin", 7, "scar", "severely stiff and shriveled skin that seems to be peeling off the body"),
    ("skin", 7, "internal", "severe paralysis of the entire body"),
    ("skin", 7, "internal_scar", "general numbness all over"),
    ("skin", 8, "external", "open and bleeding sores all over the skin"),
    ("skin", 8, "scar", "severe skin loss exposing bone and internal organs"),
    ("skin", 8, "internal", "complete paralysis of the entire body"),
    ("skin", 8, "internal_scar", "general numbness all over and have difficulty thinking"),
)
# fmt: on
