"""First Aid anatomy charts — generated from dr-scripts'
data/base-anatomy-charts.yaml by tools/anatomy_tables.py, do not edit.

CHARTS maps a chart's name, as LOOK MY COMPENDIUM lists it, to (the
word TURN MY COMPENDIUM TO finds its page by, the Scholarship it asks).
"""

# fmt: off
CHARTS = {
    'Rat': ('Rat', 0),
    'Croff Pothanit': ('Croff Pothanit', 10),
    'Heggarangi Frog': ('Heggarangi Frog', 10),
    'Brocket Deer': ('Brocket Deer', 15),
    'Scavenger Goblin': ('Scavenger', 15),
    'Wild Boar': ('Wild Boar', 20),
    'Silver Leucro': ('Silver Leucro', 20),
    'Grass Eel': ('Grass Eel', 25),
    'Striped Badger': ('Striped Badger', 25),
    'Blood Dryad': ('Blood Dryad', 30),
    'Equine': ('Equine', 30),
    'Blood Nyad': ('Blood Nyad', 35),
    'Glutinous Lipopod': ('Glutinous', 35),
    'Kelpie': ('Kelpie', 40),
    'Trollkin': ('Trollkin', 40),
    'Boggle': ('Boggle', 45),
    'Cougar': ('Cougar', 45),
    'Dwarven': ('Dwarven', 50),
    'Elothean': ('Elothean', 50),
    'Elven': ('Elven', 50),
    'Gnome': ('Gnome', 50),
    "Gor'Tog": ("Gor'Tog", 50),
    'Halfling': ('Halfling', 50),
    'Human': ('Human', 50),
    'Kaldar': ('Kaldar', 50),
    'Prydaen': ('Prydaen', 50),
    'Rakash': ('Rakash', 50),
    "S'Kra Mur": ("S'Kra Mur", 50),
    'Boobrie': ('Boobrie', 120),
    'Snow Goblin': ('Snow Goblin', 120),
    'Thunder Ram': ('Thunder Ram', 120),
    'Copperhead Viper': ('Copperhead', 140),
    'Malodorous Bucca': ('Malodorous', 140),
    'Dusk Ogre': ('Dusk Ogre', 160),
    'Young Ogre': ('Young Ogre', 160),
    'Bison': ('Bison', 180),
    'Rock Troll': ('Rock Troll', 180),
    'Sun Vulture': ('Sun Vulture', 180),
    'Fire Maiden': ('Fire Maiden', 200),
    'Moss Mey': ('Moss Mey', 200),
    'Prereni': ('Prereni', 220),
    "Vela'tohr Bloodvine": ("Vela'tohr", 220),
    'Peccary': ('Peccary', 230),
    'Blue-belly Crocodile': ('Blue-belly', 240),
    'Kashika Serpent': ('Kashika Serpent', 240),
    'River Caiman': ('River Caiman', 260),
    'Sluagh': ('Sluagh', 260),
    'Wood Troll': ('Wood Troll', 260),
    'Gidii': ('Gidii', 280),
    'Black Goblin': ('Black Goblin', 300),
    'Granite Gargoyle': ('Granite', 320),
    'Rhoat Moda': ('Rhoat Moda', 320),
    'River Sprite': ('River Sprite', 320),
    'Bawdy Swain': ('Bawdy Swain', 340),
    'Swamp Troll': ('Swamp Troll', 340),
    'Heggarangi Boar': ('Heggarangi Boar', 360),
    'Warcat': ('Warcat', 360),
    'Blacktip Shark': ('Blacktip Shark', 380),
    'Piranha': ('Piranha', 380),
    'Lanky Grey Lach': ('Lanky Grey Lach', 400),
    'Ape': ('Ape', 410),
    'Nomlas': ('Nomlas', 410),
    'Merrows': ('Merrows', 420),
    'Selkie': ('Selkie', 430),
    'Marnet': ('Marnet', 435),
    'Geni': ('Geni', 440),
    'Trekhalo': ('Trekhalo', 450),
    "Par'i Heitak": ("Par'i", 450),
    'Giant': ('Giant', 460),
    'Bobcat': ('Bobcat', 470),
    'Snowbeast': ('Snowbeast', 480),
    'Arzumos': ('Arzumos', 490),
    'River Otter': ('River Otter', 490),
    'Caracal': ('Caracal', 500),
    'Flutertae': ('Flutertae', 500),
    'Firecat': ('Firecat', 510),
    'Gryphon': ('Gryphon', 520),
    'Seordmaor': ('Seordmaor', 530),
    'Bull': ('Bull', 540),
    'Mammoth': ('Mammoth', 550),
    'Penguin': ('Penguin', 550),
    'Hawk': ('Hawk', 560),
    'Armadillo': ('Armadillo', 570),
    'Floratroll': ('Floratroll', 575),
    'Shark': ('Shark', 580),
    "La'heke": ("La'heke", 590),
    'Manatee': ('Manatee', 600),
    'Angiswaerd': ('Angiswaerd', 600),
    'Toad': ('Toad', 610),
    'Elsralael': ('Elsralael', 620),
    'Celpeze': ('Celpeze', 630),
    'Spider': ('Spider', 640),
    'Silverfish': ('Silverfish', 650),
    'Crab': ('Crab', 660),
    'Westanuryn': ('Westanuryn', 670),
    'Horse Fly': ('Horse Fly', 675),
    'Dolomar': ('Dolomar', 680),
    'Warklin': ('Warklin', 690),
    'Wasp': ('Wasp', 700),
    'Gelapod': ('Gelapod', 700),
    'Dryad': ('Dryad', 710),
    'Fendryad': ('Fendryad', 720),
    'Sprite': ('Sprite', 730),
    'Alfar': ('Alfar', 740),
    'Frostweaver': ('Frostweaver', 750),
    'Spriggan': ('Spriggan', 760),
    'Gremlin': ('Gremlin', 770),
    'Cyclops': ('Cyclops', 780),
    "Atik'et": ("Atik'et", 790),
    "S'lai": ("S'lai", 800),
    "Adan'f": ("Adan'f", 810),
    "Kra'hei": ("Kra'hei", 820),
    'Faenrae': ('Faenrae', 830),
    'Bear': ('Bear', 840),
    'Barghest': ('Barghest', 850),
    'Shalswar': ('Shalswar', 860),
    'Dyrachis': ('Dyrachis', 870),
    "Poloh'izh": ("Poloh'izh", 880),
    'Korograth': ('Korograth', 890),
    'Larva': ('Larva', 900),
    'Bizar': ('Bizar', 910),
    'Pivuh': ('Pivuh', 920),
    'Vulture': ('Vulture', 930),
    'Unyn': ('Unyn', 940),
    'Moruryn': ('Moruryn', 950),
    'Moth': ('Moth', 960),
    'Kartais': ('Kartais', 970),
    'Colepexy': ('Colepexy', 980),
    'Vykathi': ('Vykathi', 990),
    'Wyvern': ('Wyvern', 1000),
    'Elpalzi': ('Elpalzi', 1050),
    "Xala'shar": ("Xala'shar", 1050),
}
# fmt: on
