"""Creatures whose boxes the wiki lists — generated, do not edit.

Source: https://elanthipedia.play.net/Locksmithing, its "Creatures with boxes" table
(tools/box_tables.py regenerates this file). LOCKS maps a
creature's name, lowercased, to (ranks, cap, drop): the approximate
Locksmithing ranks its boxes want and teach to, and the drop rate,
"" where the table leaves it blank — the wiki's own words.
"""

# fmt: off
LOCKS = {
    "adan'f blood warrior": ('200', '??', ''),
    "adan'f shadow mage": ('200', '??', ''),
    "adan'f spirit dancer": ('276', '??', ''),
    'alley thug': ('130(?)', '??', ''),
    'arbelog': ('60', '??', ''),
    'armored shalswar': ('245', '??', ''),
    'ashu hhinvi': ('350(?)', '700', ''),
    'bawdy swain': ('75(?)', '185(?)', 'High'),
    'black goblin': ('??', '??', ''),
    'blight ogre': ('??', '??', ''),
    'blood dryad': ('0', '35', ''),
    'blood nyad': ('0', '35', ''),
    'boggle': ('30', '55', ''),
    'corsair': ('??', '??', ''),
    'crazed madmen': ('0', '35', ''),
    'crossing thug': ('100', '??', ''),
    'crypt fiend': ('??', '??', ''),
    'cutthroat': ('100', '??', ''),
    'dark fiend': ('60(?)', '??', ''),
    'dark spirit': ('130', '??', ''),
    'dragon priest assassin': ('850', '??', ''),
    'dragon priest intercessor': ('1100(??)', '??', ''),
    'dragon priest/priestess': ('245', '(similar to Armored Shalswar)', ''),
    'dusk ogre': ('50', '85', 'High'),
    'faenrae reaver': ('35', '75', ''),
    'faenrae stalker': ('??', '??', ''),
    'fendryad': ('150(?)', '??', ''),
    'fire maiden': ('55', '85(?)', ''),
    'fire sprite': ('55', '85(?)', ''),
    'footpad': ('100', '??', ''),
    'forest geni': ('150', '420(soft cap)', 'High'),
    'frostweaver': ('150', '250 softcap', ''),
    'ghoul': ('0', '35', ''),
    'goblin': ('0', '40+', 'High'),
    'goblin shaman': ('30', '55', ''),
    'goblin zombie': ('0', '35', ''),
    'granite gargoyle': ('80', '>300', 'High'),
    'greater sluagh': ('280(?)', '??', ''),
    'grendel': ('30', '55', ''),
    'gypsy marauder': ('75(?)', '105(?)', ''),
    'kobold': ('30', '55', ''),
    "kra'hei": ('260', '350?', ''),
    "kra'hei hatchling": ('130', '320 softcap', 'High'),
    'lanky grey lach': ('150', '??', ''),
    "lava field atik'et": ('??', '??', ''),
    'lesser sluagh': ('60', '??', ''),
    "lun'shele hunter": ('240?', '??', ''),
    "lun'shele trekhalo": ('240?', '??', ''),
    'maelshyvean cinder beast': ('340', '??', 'High'),
    'maelshyvean shadow beast': ('340', '??', 'High'),
    'merrows': ('115', '160', ''),
    "misshapen germish'din": ('260(?)', '??', ''),
    'moneyrubber': ('90(?)', '', ''),
    'moss mey': ('70', '105(?)', ''),
    'orc bandit': ('150', '??', ''),
    'orc clan-chief': ('??', '??', ''),
    'orc raider': ('276+', '??', 'High'),
    'orc reiver': ('200??', '??', 'High'),
    'orc scout': ('150??', '??', 'High'),
    'pale grey death spirit': ('140??', '??', ''),
    'pinchfist': ('90(?)', '', ''),
    "pirates on the lybadel//kree'la": ('110', '220', ''),
    "plain atik'et": ('??', '??', ''),
    'quartz gargoyle': ('135', '>300', 'High'),
    'red-bristled gremlin': ('205(?)', '>300', 'Medium'),
    'revenant zombie': ('30', '55', ''),
    'river sprite': ('125(?)', '??', ''),
    'rock troll': ('40', '>120', ''),
    'rotting deadwood dryad': ('150(?)', '??', ''),
    'ruffian': ('100', '??', ''),
    "s'lai scout": ('30(?)', '??', ''),
    "s'sugi malchata": ('300', '>760', ''),
    'sand sprite': ('40', '100+', 'High'),
    'scavenger troll': ('140', '>300', 'High'),
    'scout ogre': ('75(?)', '110(?)', ''),
    'shadow master': ('??', '??', ''),
    'shadoweaver': ('150(?)', '??', ''),
    'skeletal kobold headhunter': ('55', '85(?)', ''),
    'skeletal kobold savage': ('55', '85(?)', ''),
    'skeletal sailor': ('150?', '??', ''),
    'skinflint': ('90(?)', '', ''),
    'sky giant': ('350??', '??', 'High'),
    'sleazy lout': ('0', '35', 'High'),
    'snow goblin': ('85(?)', '135(?)', 'High'),
    'spectral pirate': ('150?', '??', ''),
    'super rock troll': ('??', '??', ''),
    'swamp troll': ('80', '??', ''),
    'telga moradu': ('??', '??', ''),
    "temple atik'et": ('??', '??', ''),
    'tightwad': ('90(?)', '', ''),
    'trollkin': ('0', '35', 'High'),
    "ur hhrki'izh": ('160(?)', '230(?)', ''),
    'velakan slaver': ('210(?)', '??', ''),
    'wir dinego': ('240', '350', ''),
    'wood troll': ('30', '55', ''),
    "writhing maiden's tress": ('130(?)', '??', ''),
    'young cave troll': ('85(?)', '135(?)', ''),
    'young ogre': ('75(?)', '105(?)', ''),
    'zombie head-splitter': ('600(?)', '>760', 'High'),
    'zombie kobold headhunter': ('55', '85(?)', ''),
    'zombie kobold savage': ('55', '85(?)', ''),
    'zombie mauler': ('500(?)', '>760', ''),
    'zombie nomad': ('210(?)', '??', ''),
    'zombie stomper': ('300', '>760', 'High'),
}
# fmt: on
