"""Creatures and the ranks they teach to — generated, do not edit.

Source: Elanthipedia's pages using Template:Critter via https://elanthipedia.play.net/api.php
(tools/creature_tables.py regenerates this file). CAPS maps a
creature's name, lowercased, to (level, MinCap, MaxCap): full
learning below MinCap, none past MaxCap; variants of one name keep
the highest MaxCap. level or MinCap is None where the page has none.
BOXES maps a name to the page's Has Boxes, True when any variant
has them; a page that says neither is left out.
"""

# fmt: off
CAPS = {
    'a': (1, 1, 1),
    "adan'f blood warrior": (58, 250, 325),
    "adan'f shadow mage": (58, 250, 370),
    "adan'f shadowmancer": (None, None, 2),
    "adan'f spirit dancer": (83, 425, 600),
    "adept adan'f blood warrior": (None, 350, 400),
    "adept adan'f shadow mage": (None, 350, 400),
    'adult desert armadillo': (123, 725, 1000),
    'adult razortusk boar': (21, 100, 130),
    'adult razortusk sow': (18, 80, 105),
    'adult sovamedo': (None, 600, 800),
    'adult wyvern': (160, 1000, 1350),
    'albino cave fish': (None, 50, 100),
    'alley thug': (None, 140, 230),
    'amalgamated fleshreaper': (None, 450, 600),
    'andesite gargoyle': (None, 550, 850),
    'angiswaerd hatchling': (None, 180, 250),
    'animated items': (None, 550, 850),
    'antelope': (None, 20, 43),
    'arbelog': (None, 50, 85),
    'armored shalswar': (76, 300, 400),
    'armored warklin': (65, 400, 600),
    'arthelun cabalist': (164, 1100, 1600),
    'asaren celpeze': (None, 550, 800),
    'ashu hhinvi': (100, 500, 700),
    'augmented arachnid': (None, 1, 1750),
    'avtalia scuttler': (None, 1, 1),
    'baby forest gryphon': (47, 250, 350),
    'banshee': (None, 100, 200),
    'bawdy swain': (21, 120, 150),
    'beisswurm': (9, 50, 65),
    'beltunumshi': (None, 300, 500),
    'birdcatcher spider': (60, 310, 420),
    'bison': (None, 80, 110),
    'black ape': (105, 490, 750),
    'black bear': (None, 45, 59),
    'black goblin': (105, 500, 720),
    'black marble gargoyle': (72, 330, 540),
    'blacktip shark': (None, 170, 280),
    'blood dryad': (4, 25, 40),
    'blood nyad': (4, 25, 40),
    'blood wolf': (14, 75, 90),
    'blood-thirsty lascar': (None, None, 260),
    'blue-belly crocodile': (None, 100, 159),
    'blue-dappled prereni': (40, 200, 250),
    'blue-green pivuh': (54, 220, 360),
    'blueclaw sand crab': (None, 55, 80),
    'bobcat': (10, 45, 65),
    'boggle': (5, 39, 49),
    'bone amalgam': (None, 180, 250),
    'bone wolf': (10, 55, 73),
    'bone wyvern': (195, 1450, 1750),
    'bony fylgja': (None, 250, 400),
    'boobrie': (None, 50, 75),
    'bristleback peccary': (58, 280, 400),
    'brittle skeletal peon': (None, 25, 50),
    'brown bear': (None, 45, 59),
    'brown burrower': (5, 18, 42),
    'brown tree snake': (12, 60, 75),
    'buccaneer': (None, None, 260),
    'bull shark': (None, 180, 350),
    'cadaverous blue-belly crocodile': (None, 100, 160),
    'cadaverous yeehar': (None, 150, 300),
    'caracal': (None, 225, 345),
    'cave bear': (10, 45, 65),
    'cave troll': (None, 240, 375),
    'cavern bear': (None, 350, 450),
    'cinderwing harpy': (None, 1450, 1750),
    'cinnamon bear': (None, 250, 350),
    'clay slayer': (None, 625, 925),
    'clouded arzumos': (None, 230, 340),
    'copperhead viper': (11, 55, 70),
    'corpse grub': (None, 25, 45),
    "corrupted khor'vela beltunumshi": (None, 0, 2000),
    'cougar': (6, 30, 49),
    'crag': (None, 160, 185),
    'crauyarin scuttler': (None, 515, 725),
    'crazed madman': (4, 15, 45),
    'croff pothanit': (4, 22, 39),
    'crypt fiend': (20, 100, 145),
    'cutthroat': (25, 110, 175),
    'damaska boar': (80, 390, 400),
    'dark fiend': (None, 60, 75),
    'dark spirit': (None, 235, 300),
    'dark sprite': (None, 230, 370),
    'decaying blightwater nyad': (None, 150, 250),
    'deer': (4, 25, 45),
    'dengizen drake': (None, 1100, 1500),
    'dinnsehencha': (150, 800, 1300),
    'dire bear': (None, 120, 170),
    'disheveled ghoul crow': (28, 130, 175),
    'dobek moruryn': (62, 300, 450),
    'dragon priest and priestess': (None, 350, 500),
    'dragon priest assassin': (150, 750, 1100),
    'dragon priest crone': (76, 375, 425),
    'dragon priest fanatic': (None, 55, 90),
    'dragon priest intercessor': (170, 950, 1300),
    'dragon priest juggernaut': (76, 400, 500),
    'dragon priest purifier': (76, 350, 490),
    'dragon priest sentinel': (76, 300, 460),
    'dragon priest zealot': (76, 400, 520),
    'drowned one': (None, 90, 150),
    'dryad priestess': (34, 175, 220),
    'dryanoxie': (None, 450, 630),
    'dusk ogre': (10, 60, 75),
    'dusky scythewing moth': (29, 150, 190),
    'eidolon steed': (1, 100, 125),
    'elba darvager': (49, 260, 325),
    "elder adan'f blademaster": (190, 1500, 1750),
    "elder adan'f sorcerer": (190, 1500, 1750),
    'elder blue-dappled prereni': (50, 250, 300),
    'elder desert armadillo': (143, 700, 1100),
    'elder razortusk boar': (35, 130, 230),
    'elder red brocket deer': (None, 200, 260),
    'elder storm geese': (30, 130, 180),
    "elite adan'f spirit dancer": (None, None, 660),
    'elpalzi partisan': (None, 100, 160),
    'emaciated umbramagus': (None, 250, 340),
    'ember bull': (None, 300, 400),
    'emerald claw troll': (None, 450, 650),
    'endrus serpent': (15, 70, 95),
    'enraged tusky': (None, 500, 750),
    'etes drone': (None, 120, 175),
    'faenrae assassin': (67, 375, 500),
    'faenrae executioner': (None, None, 500),
    'faenrae reaver': (8, 35, 52),
    'faenrae stalker': (None, 225, 300),
    'fell hog': (2, 10, 40),
    'feral banyakea': (None, 600, 800),
    'feral bone mastiff': (None, 245, 310),
    'ferocious foothill fighter': (None, 100, 140),
    'field goblin': (None, 17, 42),
    'fire maiden': (None, 80, 100),
    'fire sprite': (None, 60, 75),
    'fledgling forest gryphon': (58, 280, 400),
    'fluffy stolb': (None, 700, 1000),
    'footpad': (25, 110, 150),
    'forager ghoul': (130, 600, 800),
    'forager goblin': (2, 12, 34),
    'forest bandit': (None, 210, 240),
    'forest geni': (50, 250, 350),
    'fractured revivified mutt': (None, 0, 35),
    'frager wight': (142, 750, 1000),
    'frost angiswaerd': (None, 260, 340),
    'frost troll': (None, 1400, 1750),
    'frostweaver': (40, 180, 260),
    'frostweyr bear': (34, 175, 225),
    'fuligin umbral moth': (170, 1100, 1500),
    'gale drake': (None, 1000, 1300),
    'gam chaga': (68, 300, 450),
    'gargantuan bone golem': (None, 325, 380),
    'gatekeeper skeleton': (None, None, 85),
    'gestalt void midge': (None, 300, 500),
    'ghoul': (5, 26, 44),
    'ghoul raven': (56, 280, 380),
    'giant bear': (45, 210, 280),
    'giant black leucro': (38, 180, 230),
    'giant blade spider': (None, 300, 400),
    'giant blight bat': (25, 90, 170),
    'giant blight ogre': (44, 180, 250),
    'giant snow hawk': (111, 460, 670),
    'giant thicket viper': (30, 130, 180),
    'giant wasp': (2, 35, 50),
    'gigantic lachmate': (None, 375, 625),
    'glazed clay slayer': (None, 750, 1200),
    'glistening scythewing larvae': (None, 85, 100),
    'glutinous lipopod': (None, 32, 50),
    'gnarled fendryad': (None, 190, 280),
    'goblin bowman': (None, 130, 170),
    'goblin shaman': (4, 20, 50),
    'goblin zombie': (None, 15, 45),
    'gold-taloned elder forest gryphon': (90, 380, 600),
    'golden pard': (None, 180, 240),
    "golden/red-gold scaled atik'et": (None, 120, 170),
    'granite gargoyle': (19, 95, 125),
    'grass eel': (None, 45, 60),
    'grave worm': (21, 90, 130),
    'graverobber': (70, 270, 420),
    'greater ghoul raven': (None, 350, 450),
    'greater shadow hound': (67, 270, 380),
    'greater water sprite': (20, 100, 130),
    'grendel': (5, 35, 50),
    'grey clay archer': (None, 180, 240),
    'grey clay mage': (None, 175, 250),
    'grey clay soldier': (50, 150, 240),
    'grizzled red leucro': (None, 180, 225),
    'gypsy marauder': (None, 100, 125),
    'haizen drake': (None, 1000, 1300),
    'hammerhead shark': (55, 1800, 300),
    'hardened silverfish': (None, 55, 75),
    'haunt': (None, 100, 200),
    'heggarangi boar': (None, 150, 200),
    'heggarangi frog': (1, 0, 26),
    'huge spider crab': (None, 300, 450),
    'hulking black barghest': (None, 210, 290),
    'hurricane drake': (None, 1200, 1600),
    'ice archon': (174, 1200, 1650),
    'ichorous ossein amalgam': (None, 60, 80),
    'icy blue ghast': (None, 280, 430),
    'immature firecat': (None, 90, 125),
    'inkhorne': (5, 20, 45),
    'isundjen conjurer': (None, 360, 460),
    'jackal': (None, 36, 50),
    'jeol moradu': (175, 1200, 1500),
    'juvenile desert armadillo': (None, 700, 900),
    'juvenile wyvern': (143, 700, 1100),
    'kelpie': (3, 35, 50),
    'kobold': (None, 36, 49),
    "kra'hei": (70, 300, 400),
    "kra'hei hatchling": (30, 130, 190),
    'lachmate': (41, 150, 250),
    'lanky grey lach': (None, 210, 316),
    'large brown spider': (3, 36, 51),
    'large musk hog': (2, 15, 35),
    'lava drake': (155, 900, 1300),
    'leathery grey ghoul': (None, 250, 350),
    'lesser dusky-scaled basilisk': (72, 300, 520),
    'lesser north wind banshee': (160, 900, 1300),
    'lesser shadow hound': (33, 160, 210),
    'lesser skeleton': (4, 12, 28),
    'lesser sluagh': (34, 150, 200),
    'lithe blight ogre': (33, 140, 150),
    'long-fanged warcat': (None, 220, 300),
    "lun'shele hunter": (None, 310, 430),
    "lun'shele trekhalo": (None, 370, 530),
    'maelshyvean cinder beast': (79, 350, 570),
    'maelshyvean hierophant': (101, 575, 700),
    'maelshyvean shadow beast': (79, 320, 650),
    'magma cobra': (None, 1450, 1750),
    'malodorous bucca': (12, 50, 65),
    'mange-covered rotting prydaen': (None, 60, 100),
    'mange-covered rotting rakash': (None, 60, 100),
    'marbled angiswaerd': (None, 300, 400),
    "matron's tress": (None, 175, 250),
    'meadow ram': (None, 45, 70),
    'meandering mountain marauder': (None, 100, 125),
    'merrows': (23, 120, 150),
    'miniscule animated items': (None, 40, 70),
    'misenseor resuscitant': (107, 550, 800),
    'miserly moneygrubber': (None, 100, 150),
    "misshapen germish'din": (None, 330, 520),
    'misty black zephyr': (None, 525, 760),
    'moltspun boggle': (None, 70, 90),
    'morah creeper': (17, 70, 140),
    'morah vine': (None, 70, 120),
    'moss mey': (23, 90, 135),
    'mottled westanuryn': (None, 180, 290),
    'mountain giant': (72, 375, 530),
    'muscular firecat': (None, 280, 430),
    'muscular ghoulish slayer': (None, 250, 550),
    'musk hog': (2, 10, 35),
    'mutant togball': (None, 130, 165),
    'mutilated transmogrified oaf': (None, 70, 140),
    'nightreaver unyn': (40, 150, 225),
    'nightstalker unyn': (57, 280, 350),
    'nightweaver unyn': (28, 120, 188),
    'nimbus': (None, 250, 320),
    'nipoh oshu': (70, 240, 350),
    'noxious flea-ridden beast': (None, 80, 140),
    "ochre la'heke": (45, 180, 240),
    'onyx gargoyle': (63, 320, 400),
    'orc bandit': (None, 180, 317),
    'orc clan-chief': (74, 400, 500),
    'orc raider': (65, 380, 450),
    'orc reiver': (54, 280, 350),
    'orc scout': (None, 180, 230),
    'orc slasher': (None, 600, 800),
    'origami': (3, 20, 55),
    'pale grey death spirit': (35, 200, 250),
    'pale grey death squirrel': (2, 10, 35),
    "par'i heitak": (None, 400, 700),
    'peccary': (34, 225, 300),
    'piranha': (None, 275, 420),
    'pirate': (None, 140, 175),
    'pirate zombie': (None, 200, 350),
    'piruati serpent': (25, 100, 150),
    "poloh'izh": (None, 500, 700),
    'preserved zombified prydaen': (None, 240, 350),
    'pugnacious pinchfist': (None, 100, 160),
    'putrid tree snake': (None, 100, 130),
    'quartz gargoyle': (None, 135, 190),
    'ragged wind hag': (135, 700, 950),
    'rat': (1, 0, 30),
    'rebel mercenary': (85, 500, 700),
    'red brocket deer': (None, 135, 180),
    'red-bristled gremlin': (None, 250, 400),
    "red-gold scaled atik'et": (None, 280, 430),
    'retan dolomar': (61, 260, 410),
    'retch fiend': (28, 125, 175),
    'revenant conscript': (6, 25, 50),
    'revenant zombie': (8, 45, 59),
    'rhoat moda': (None, 190, 280),
    'rigger': (None, 100, 260),
    'ring-necked gidii': (4, 15, 44),
    'river boa': (None, 275, 350),
    'river sprite': (31, 140, 190),
    'robed banyakea': (None, 550, 750),
    'rock guardian': (45, 210, 290),
    'rock troll': (None, 80, 115),
    'rotting deadwood dryad': (36, 150, 250),
    'ruby-crested adult forest gryphon': (89, 300, 550),
    'ruffian': (25, 110, 150),
    "s'lai scout": (5, 36, 49),
    "s'lai screamer": (None, 250, 340),
    "s'sugi malchata": (104, 500, 700),
    'sabre-toothed warcat': (51, 280, 350),
    'saendalen shark': (None, 300, 475),
    'sailfin lizard': (None, 300, 500),
    'salt crab': (None, 25, 42),
    'salt golem': (None, 500, 700),
    'sand spider': (15, 80, 100),
    'sand sprite': (11, 50, 73),
    'savannah bull': (90, 550, 750),
    'scaly seordmaor': (78, 400, 530),
    'scavenger giant': (185, 1450, 1750),
    'scavenger goblin': (3, 18, 36),
    'scavenger troll': (27, 170, 220),
    'scout ogre': (22, 120, 160),
    'seething summit sunderer': (None, 130, 175),
    'selkie': (None, 200, 300),
    'seordavor kartais': (None, 180, 230),
    'shadefield eviscerator': (None, 200, 290),
    'shadewing harpy': (120, 700, 900),
    'shadoweaver': (None, 150, 255),
    'shadowfrost moth': (195, 1450, 1750),
    'shaggy black barghest': (None, 120, 180),
    'shambling frostcrone': (None, 180, 340),
    'shifty-eyed skinflint': (None, 100, 150),
    'sickly blightwater nyad': (39, 160, 250),
    'silver leucro': (16, 85, 101),
    'silver-backed bear': (17, 85, 105),
    'silver-grey cloud rat': (None, 300, 420),
    'silverfish': (14, 75, 90),
    'sinuous elsralael': (None, 300, 350),
    'sinuous ice adder': (50, 200, 300),
    'skeletal kobold headhunter': (None, 85, 110),
    'skeletal kobold savage': (None, 85, 110),
    'skeletal sailor': (None, 210, 300),
    'skunk': (1, 18, 42),
    'sky giant': (105, 550, 700),
    'sleazy lout': (2, 0, 35),
    "sleek hele'la": (None, 250, 360),
    'small birdcatcher spider': (12, 60, 75),
    'small peccary': (None, 175, 250),
    'small tree sloth': (None, 150, 200),
    'small zombie piranha': (None, 100, 250),
    'snaer hafwa': (82, 380, 600),
    'snarling bronze leucro': (None, 600, 800),
    'snarlvine fox': (None, 550, 700),
    'snippet': (None, 70, 100),
    'snow goblin': (30, 140, 175),
    'snowbeast': (18, 75, 105),
    'sovamedo cub': (None, 220, 320),
    'spectacled river caiman': (None, 60, 90),
    'spectral pirate': (45, 250, 325),
    'spiny dyrachis': (34, 140, 200),
    'spotted bobcat': (None, 65, 80),
    'spotted kashika serpent': (None, 100, 160),
    'spotted shark': (None, 90, 115),
    'stone-throwing imp': (12, 55, 70),
    'storm bull': (113, 550, 800),
    'striped badger': (3, 19, 42),
    'stumpy blight ogre': (39, 150, 230),
    'stunted undead gerbil': (10, 45, 70),
    'sun vulture': (15, 70, 100),
    'supple firecat': (None, 300, 430),
    'suw bizar': (None, 70, 90),
    'swamp troll': (None, 190, 260),
    'sylph': (None, 150, 250),
    'telga moradu': (None, 360, 400),
    'telga orek': (151, 800, 1300),
    'thornkin': (None, 1400, 1750),
    'thug': (25, 110, 150),
    'thunder ram': (None, 47, 70),
    'tiger shark': (None, 190, 290),
    'tortured soul': (None, 0, 2000),
    'transparent shylvic': (None, 240, 325),
    'tree snake': (60, 300, 420),
    'treehopper toad': (None, 300, 400),
    'trollkin': (5, 33, 40),
    'troublesome tightwad': (None, 100, 150),
    'twisted dryad': (36, 175, 220),
    'twisted fendryad': (None, 190, 280),
    'umbral moth': (178, 950, 1400),
    'unctuous prydaen zombie': (None, 340, 530),
    'undead gerbil': (25, 100, 145),
    "ur hhrki'izh": (44, 225, 275),
    'ur-maeldryth': (200, 1600, 1750),
    "vela'tohr bloodvine": (27, 120, 170),
    'velakan slaver': (None, 225, 360),
    'vicious dragon priest intercessor': (171, 1100, 1600),
    'vicious warcat': (None, 160, 230),
    'vile plague wraith': (89, 450, 650),
    'void black umbral moth': (185, 1450, 1750),
    'vykathi builder': (None, 120, 170),
    'vykathi excavator': (None, 120, 170),
    'vykathi harvester': (None, 160, 220),
    'vykathi reaper': (None, 200, 280),
    'vykathi soldier': (None, 200, 280),
    'war mammoth': (None, 380, 610),
    'warklin mauler': (66, 400, 500),
    'wary whispering warrior': (None, 110, 150),
    'water sprite': (7, 28, 45),
    'whitetip shark': (None, 200, 350),
    'wild boar': (4, 18, 42),
    'wildland goblin': (None, 17, 42),
    'wind hound': (8, 35, 73),
    'windbag': (None, 200, 300),
    'wir dinego': (72, 360, 450),
    'wolf spider': (None, 70, 98),
    'wood troll': (None, 100, 145),
    'wormwood vine': (None, 120, 190),
    "writhing maiden's tress": (31, 120, 215),
    "xala'shar archer": (158, 900, 1300),
    "xala'shar archimage": (154, 900, 1350),
    "xala'shar conjurer": (142, 800, 1100),
    "xala'shar magus": (140, 750, 1000),
    "xala'shar overseer": (165, 950, 1400),
    "xala'shar shredder": (165, 950, 1400),
    "xala'shar slayer": (162, 900, 1300),
    "xala'shar thrall": (138, 750, 1000),
    "xala'shar vanquisher": (156, 800, 1100),
    "xala'shar vindicator": (163, 900, 1350),
    'yellow-bristled gremlin': (None, 280, 410),
    'young blue-dappled prereni': (30, 130, 180),
    'young cave troll': (22, 85, 170),
    'young desumos': (None, 250, 1),
    'young firecat': (None, 90, 140),
    'young forest gryphon': (60, 300, 420),
    'young ogre': (19, 90, 120),
    'young red brocket deer': (None, 90, 110),
    'young wyvern': (124, 600, 900),
    "yvhh la'tami": (None, 160, 200),
    'zombie boar': (35, 130, 230),
    'zombie goblin': (None, 0, 35),
    'zombie head-splitter': (105, 600, 733),
    'zombie kobold headhunter': (None, 85, 110),
    'zombie kobold savage': (None, 85, 110),
    'zombie mauler': (92, 500, 670),
    'zombie nomad': (None, 260, 410),
    'zombie red leucro': (None, 130, 180),
    'zombie stomper': (84, 460, 625),
}

BOXES = {
    'a': True,
    'abominable umbral race': True,
    "adan'f blood warrior": True,
    "adan'f shadow mage": True,
    "adan'f shadowmancer": True,
    "adan'f spirit dancer": True,
    "adept adan'f blood warrior": True,
    "adept adan'f shadow mage": True,
    'adult desert armadillo': False,
    'adult razortusk boar': False,
    'adult razortusk sow': False,
    'adult sovamedo': False,
    'adult wyvern': False,
    'alley thug': True,
    'ambulatory coral reef with labyrinthine grooves': False,
    'andesite gargoyle': True,
    'andesite guardian': False,
    'angiswaerd hatchling': False,
    'animated items': False,
    'antelope': False,
    'arbelog': True,
    'arisen ghoulish beggar': True,
    'arisen ghoulish farmer': True,
    'arisen ghoulish fisher': True,
    'arisen ghoulish guard': True,
    'arisen ghoulish socialite': True,
    'arisen ghoulish teacher': True,
    'arisen ghoulish villager': True,
    'armored shalswar': True,
    'armored warklin': False,
    'arthelun cabalist': True,
    'asaren celpeze': False,
    'ashu hhinvi': True,
    'augmented arachnid': False,
    'avtalia scuttler': False,
    'baby forest gryphon': False,
    'banshee': False,
    'bawdy swain': True,
    'beisswurm': False,
    'beltunumshi': False,
    'birdcatcher spider': False,
    'bison': False,
    'black ape': False,
    'black bear': False,
    'black fang deadeye': True,
    'black fang recruit': True,
    'black fang watcher': True,
    'black goblin': True,
    'black marble gargoyle': True,
    'black pard': False,
    'blacktip shark': False,
    'blight locust': True,
    'blood dryad': True,
    'blood nyad': True,
    'blood wolf': False,
    'blue-belly crocodile': False,
    'blue-dappled prereni': False,
    'blue-green pivuh': False,
    'blueclaw sand crab': False,
    'bobcat': False,
    'bogfen golem': True,
    'boggle': True,
    'bone amalgam': False,
    'bone wolf': False,
    'bone wyvern': False,
    'bony fylgja': False,
    'bony wind wretch': True,
    'boobrie': False,
    'breccia guardian': False,
    'bristleback peccary': False,
    'brown bear': False,
    'brown burrower': False,
    'brown tree snake': False,
    'bull shark': False,
    'cadaverous blue-belly crocodile': False,
    'cadaverous yeehar': True,
    'caracal': False,
    'cave bear': False,
    'cave troll': True,
    'cavern bear': False,
    'cinderwing harpy': True,
    'cinnamon bear': False,
    'clay slayer': True,
    'clockwork assistant': False,
    'clockwork monstrosity': True,
    'cloud eel': False,
    'clouded arzumos': False,
    'copperhead viper': False,
    'corpse grub': False,
    "corrupted khor'vela beltunumshi": False,
    'corsair': True,
    'cougar': False,
    'crag': True,
    'crauyarin scuttler': False,
    'crazed madman': True,
    'croff pothanit': False,
    'cross-eyed libger': False,
    'crypt fiend': True,
    'cutthroat': True,
    'damaska boar': False,
    'dark fiend': True,
    'dark spirit': True,
    'dark sprite': True,
    'decaying blightwater nyad': True,
    'decomposing merelew': True,
    'deeplight fish': False,
    'deer': False,
    'dengizen drake': False,
    'dinnsehencha': True,
    'dire bear': False,
    'dirt construct': False,
    'disheveled ghoul crow': False,
    'dobek moruryn': False,
    'dragon priest and priestess': True,
    'dragon priest assassin': True,
    'dragon priest crone': True,
    'dragon priest fanatic': True,
    'dragon priest intercessor': True,
    'dragon priest juggernaut': True,
    'dragon priest purifier': True,
    'dragon priest sentinel': True,
    'dragon priest zealot': True,
    'drogor avatar': False,
    'drogorian stormrider': False,
    'drowned one': True,
    'dryad priestess': True,
    'dryanoxie': True,
    'dusk ogre': True,
    'dusky scythewing moth': False,
    'eidolon steed': False,
    'elba darvager': True,
    "elder adan'f blademaster": True,
    "elder adan'f sorcerer": True,
    'elder blue-dappled prereni': False,
    'elder desert armadillo': False,
    'elder razortusk boar': False,
    'elder red brocket deer': False,
    'elder storm geese': False,
    "elite adan'f spirit dancer": True,
    'elpalzi bowyer': True,
    'elpalzi captain': True,
    'elpalzi commander': True,
    'elpalzi elder general': True,
    'elpalzi fomenter': True,
    'elpalzi hunter': True,
    'elpalzi incendiary': True,
    'elpalzi instigator': True,
    'elpalzi mage': True,
    'elpalzi major': True,
    'elpalzi malcontent': True,
    'elpalzi officer': True,
    'elpalzi partisan': True,
    'elpalzi scout': True,
    'elpalzi soldier': True,
    'elpalzi swordsman': True,
    'elpalzi toxophilite': True,
    'elpalzi veteran': True,
    'elpazi deadeye': True,
    'elpazi dissident': True,
    'elpazi rebel': True,
    'elpazi sharpshooter': True,
    'emaciated umbramagus': False,
    'ember bull': False,
    'emerald claw troll': True,
    'endrus serpent': False,
    'enraged tusky': False,
    'ersatz': True,
    'essence of the depths': False,
    'etes drone': True,
    'faenrae assassin': True,
    'faenrae executioner': True,
    'faenrae reaver': True,
    'faenrae stalker': True,
    'fell hog': False,
    'feral banyakea': True,
    'feral bone mastiff': False,
    'ferocious foothill fighter': True,
    'festival bandit': True,
    'field goblin': True,
    'fire maiden': True,
    'fire sprite': True,
    'fledgling forest gryphon': False,
    'fluffy stolb': True,
    'footpad': True,
    'forager ghoul': True,
    'forager goblin': True,
    'forest bandit': True,
    'forest drake': False,
    'forest geni': True,
    'frager wight': True,
    'frail darkened silhouette': True,
    'frost angiswaerd': False,
    'frost troll': True,
    'frostweaver': True,
    'frostweyr bear': False,
    'fuligin umbral moth': False,
    'gale drake': False,
    'gam chaga': False,
    'gargantuan bone golem': True,
    'gatekeeper skeleton': True,
    'gaunt shadow master': True,
    'gelv cyclops': True,
    'gestalt void midge': False,
    'ghoul': True,
    'ghoul raven': False,
    'giant adder': False,
    'giant bear': False,
    'giant black leucro': False,
    'giant blade spider': False,
    'giant blight bat': False,
    'giant blight ogre': True,
    'giant gatekeeper skeleton': True,
    'giant mechanical mouse': True,
    'giant snow hawk': False,
    'giant thicket viper': False,
    'giant wasp': False,
    'gigantic lachmate': True,
    'glass construct': False,
    'glazed clay slayer': True,
    'glistening scythewing larvae': False,
    'glutinous lipopod': False,
    'gnarled fendryad': True,
    'goblin archer': True,
    'goblin chieftan': True,
    'goblin prince': True,
    'goblin shaman': True,
    'goblin skirmisher': True,
    'goblin warlord': True,
    'goblin warrior': True,
    'goblin zombie': True,
    'gold-taloned elder forest gryphon': False,
    'golden pard': False,
    "golden/red-gold scaled atik'et": True,
    'gorbesh archer': True,
    'gorbesh captain': True,
    'gorbesh commander': True,
    'gorbesh enchanter': True,
    'gorbesh line soldier': True,
    'gorbesh mage': True,
    'granite gargoyle': True,
    'grass eel': False,
    'grave worm': False,
    'graverobber': True,
    'greater ghoul raven': False,
    'greater shadow hound': False,
    'greater sluagh': True,
    'greater water sprite': False,
    'green sewer eel': False,
    'grendel': True,
    'grey clay archer': True,
    'grey clay mage': True,
    'grey clay soldier': True,
    'grizzled red leucro': False,
    'gypsy marauder': True,
    'haizen drake': False,
    'hammerhead shark': False,
    "harawep's spider": False,
    'hardened silverfish': False,
    'haunt': False,
    'heggarangi boar': False,
    'heggarangi frog': False,
    'horse': False,
    'huge spider crab': False,
    'hulking black barghest': False,
    'hurricane drake': False,
    'ice archon': True,
    'ichorous ossein amalgam': True,
    'icy blue ghast': False,
    'ilva the shrike': True,
    'immature firecat': False,
    'inkbound leonine guardian': True,
    'inkbound lupine guardian': True,
    'inkbound strigine guardian': True,
    'inkhorne': False,
    'inquisitorial deacon': True,
    'isundjen conjurer': True,
    'jackal': False,
    'jeol moradu': True,
    'juvenile desert armadillo': False,
    'juvenile wyvern': False,
    'kather shaman': False,
    'kather warrior': False,
    'kather watcher': False,
    'kelpie': False,
    'kobold': True,
    "kra'hei": True,
    "kra'hei hatchling": True,
    'lachmate': True,
    'lanky grey lach': True,
    'large brown spider': False,
    'large musk hog': False,
    'lava drake': False,
    'lesser dusky-scaled basilisk': False,
    'lesser north wind banshee': False,
    'lesser shadow hound': False,
    'lesser skeleton': True,
    'lesser sluagh': True,
    'lesser voltaic custodian': False,
    'lithe blight ogre': True,
    'long-fanged warcat': False,
    "lun'shele hunter": True,
    "lun'shele trekhalo": True,
    'maelshyvean cinder beast': True,
    'maelshyvean hierophant': True,
    'maelshyvean shadow beast': True,
    'magma cobra': False,
    'malodorous bucca': True,
    'mange-covered rotting prydaen': True,
    'mange-covered rotting rakash': True,
    'mapha arzumos': False,
    'marbled angiswaerd': False,
    "matron's tress": True,
    'meadow ram': False,
    'meandering mountain marauder': True,
    'merrows': True,
    'mimic': False,
    'miniscule animated items': False,
    'misenseor resuscitant': True,
    'miserly moneygrubber': True,
    "misshapen germish'din": True,
    'misty black zephyr': False,
    'moltspun boggle': True,
    'morah creeper': False,
    'morah vine': False,
    'moss mey': True,
    'mottled westanuryn': False,
    'mountain giant': True,
    'mummer': True,
    'murder crow': False,
    'muscular firecat': False,
    'musk hog': False,
    'mutant togball': False,
    'mutilated transmogrified oaf': True,
    'nacre-plated torbisan decapod': False,
    'nightreaver unyn': False,
    'nightstalker unyn': False,
    'nightweaver unyn': False,
    'nimbus': False,
    'nipoh oshu': False,
    'noxious flea-ridden beast': True,
    "ochre la'heke": False,
    'onyx gargoyle': True,
    'orc archer': True,
    'orc bandit': True,
    'orc clan-chief': True,
    'orc gladiator': True,
    'orc hunter': True,
    'orc marauder': True,
    'orc marksman': True,
    'orc mercenary': True,
    'orc novice': True,
    'orc raider': True,
    'orc ranger': True,
    'orc reiver': True,
    'orc savage': True,
    'orc scout': True,
    'orc skirmisher': True,
    'orc slasher': True,
    'origami': False,
    'pale grey death spirit': True,
    'pale grey death squirrel': False,
    "par'i heitak": False,
    'peccary': False,
    'piranha': False,
    'pirate': True,
    'pirate zombie': True,
    'piruati serpent': False,
    "poloh'izh": False,
    'profane destroyer': True,
    'pugnacious pinchfist': True,
    'putrefying shambler': True,
    'putrid tree snake': False,
    'quartz gargoyle': True,
    'race-eating mantrap': False,
    'rafflesia': True,
    'ragged wind hag': True,
    'rat': False,
    'red brocket deer': False,
    'red-bristled gremlin': True,
    "red-gold scaled atik'et": True,
    'retan dolomar': False,
    'retch fiend': True,
    'revenant conscript': True,
    'revenant zombie': True,
    'rhoat moda': False,
    'ring-necked gidii': False,
    'river boa': False,
    'river sprite': True,
    'robed banyakea': True,
    'rock guardian': False,
    'rock troll': True,
    'rockclaw lobster covered with algae tufts': False,
    'rotting deadwood dryad': True,
    'rough-hewn doll': True,
    'ruby-crested adult forest gryphon': False,
    'ruffian': True,
    "s'kra kor dancer": False,
    "s'kra kor shaman": True,
    "s'kra kor villager": True,
    "s'kra kor warrior": True,
    "s'lai scout": True,
    "s'sugi malchata": True,
    'sabre-toothed warcat': False,
    'saendalen shark': False,
    'sailfin lizard': False,
    'sailor': False,
    'salt crab': False,
    'salt golem': True,
    'sand spider': False,
    'sand sprite': True,
    'sandstone golem': False,
    'savannah bull': False,
    'scaly seordmaor': False,
    'scavenger giant': True,
    'scavenger goblin': True,
    'scavenger troll': True,
    'scout ogre': True,
    'seething summit sunderer': True,
    'selkie': False,
    'seordavor kartais': False,
    'shadefield eviscerator': False,
    'shadewing harpy': True,
    'shadoweaver': True,
    'shadowfrost moth': False,
    'shaggy black barghest': False,
    'shambling frostcrone': True,
    'shambling horror': True,
    'shifty-eyed skinflint': True,
    'sickly blightwater nyad': True,
    'silver leucro': False,
    'silver-backed bear': False,
    'silver-grey cloud rat': False,
    'silver-tipped mature forest gryphon': False,
    'silverfish': False,
    'sinuous elsralael': False,
    'sinuous ice adder': False,
    'skeletal kobold headhunter': True,
    'skeletal kobold savage': True,
    'skeletal sailor': True,
    'skunk': False,
    'sky giant': True,
    'sleazy lout': True,
    "sleek hele'la": False,
    'slender ribbon adder': False,
    'small birdcatcher spider': False,
    'small peccary': False,
    'small tree sloth': False,
    'small zombie piranha': False,
    'snaer hafwa': False,
    'snarling bronze leucro': False,
    'snarlvine fox': False,
    'snippet': False,
    'snow goblin': True,
    'snowbeast': False,
    'sovamedo cub': False,
    'spectacled river caiman': False,
    'spectral pirate': True,
    'spectral reaper': False,
    'spiny bloodfish': False,
    'spiny dyrachis': False,
    'spotted bobcat': False,
    'spotted kashika serpent': False,
    'spotted shark': False,
    'stalwart asketian herald': True,
    'starcrasher': False,
    'stone-throwing imp': False,
    'storm bull': False,
    'striped badger': False,
    'stumpy blight ogre': True,
    'stunted undead gerbil': False,
    'sun vulture': False,
    'supple firecat': False,
    'suw bizar': False,
    'swamp troll': True,
    'sylph': False,
    'telga moradu': True,
    'telga orek': False,
    'thornkin': True,
    'thug': True,
    'thunder eel': False,
    'thunder ram': False,
    'tiger shark': False,
    'tortured soul': False,
    'transparent shylvic': True,
    'tree snake': False,
    'treehopper toad': False,
    'trollkin': True,
    'troublesome tightwad': True,
    'twisted dryad': True,
    'twisted fendryad': True,
    'umbral moth': False,
    'unctuous prydaen zombie': True,
    'unctuous rakash zombie': True,
    'undead gerbil': False,
    "ur hhrki'izh": True,
    'ur-maeldryth': False,
    'vaporous blood wraith': True,
    "vela'tohr bloodvine": False,
    'velakan slaver': True,
    'velver': False,
    'veteran orc archer': True,
    'veteran orc skirmisher': True,
    'vicious dragon priest intercessor': True,
    'vicious ribbon adder': False,
    'vicious warcat': False,
    'vile plague wraith': True,
    'void black umbral moth': False,
    'voidspawn': False,
    'vykathi builder': False,
    'vykathi excavator': False,
    'vykathi harvester': False,
    'vykathi reaper': False,
    'vykathi soldier': False,
    'war mammoth': False,
    'warklin mauler': False,
    'wary whispering warrior': True,
    'water sprite': False,
    'wee teardrinker': False,
    'white marble gargoyle': True,
    'whitetip shark': False,
    'wild boar': False,
    'wildland goblin': True,
    'wind hound': False,
    'windbag': True,
    'winged black marble gargoyle': True,
    'wir dinego': True,
    'wolf spider': False,
    'wood troll': True,
    'wormwood vine': False,
    "writhing maiden's tress": True,
    "xala'shar archer": True,
    "xala'shar archimage": True,
    "xala'shar conjurer": True,
    "xala'shar lookout": False,
    "xala'shar magus": True,
    "xala'shar overseer": True,
    "xala'shar shredder": True,
    "xala'shar slayer": True,
    "xala'shar thrall": True,
    "xala'shar vanquisher": True,
    "xala'shar vindicator": True,
    'yellow-bristled gremlin': True,
    'young blue-dappled prereni': False,
    'young cave troll': True,
    'young desumos': False,
    'young firecat': False,
    'young forest gryphon': False,
    'young ogre': True,
    'young red brocket deer': False,
    'young wyvern': False,
    "yvhh la'tami": False,
    'zenzic': False,
    'zombie boar': False,
    'zombie goblin': True,
    'zombie head-splitter': True,
    'zombie kobold headhunter': True,
    'zombie kobold savage': True,
    'zombie mauler': True,
    'zombie nomad': True,
    'zombie red leucro': False,
    'zombie ruffian': False,
    'zombie stomper': True,
}
# fmt: on
