"""Healing herbs and where shops stock them — generated, do not edit.

Source: https://elanthipedia.play.net/Healing_herbs (tools/herb_tables.py regenerates this file).
HERBS rows are (name, foraging ranks, season, time, conditions,
terrain, body part healed, location, kind) in the wiki's own words:
part is one of its body parts (all, limb, torso, skinnerve, ...),
location is internal, external or internal/external, kind is wounds
or scars; an item that heals nothing by itself carries blanks.
SHOPS rows are (product, stores) from the availability table.
"""

# fmt: off
HERBS = (
    ('aevaes leaves', 335, 'all', 'all', '', 'boreal forest, chaparral, coastal, deciduous forest', 'eye', 'internal', 'wounds'),
    ('aloe leaves', 50, 'all', 'all', '', 'badland, desert, scrub and thorn', 'skinnerve', 'internal/external', 'wounds'),
    ('ashen flamestalk', 625, 'all', 'all', '', 'photophobic, subterranean', 'all', 'internal', 'wounds'),
    ('belradi moss', None, 'all', 'all', '', 'freshwater wetland, subterranean', 'all', 'internal', 'scars'),
    ('blocil berries', 120, 'spring, summer, fall', 'all', '', 'freshwater wetland, rural cultivated, urban cultivated', 'limb', 'external', 'scars'),
    ('blue flower', 42, 'winter', 'all', '', '', '', 'internal', ''),
    ('cebi root', 275, 'all', 'all', '', 'rural cultivated, steppe, urban cultivated', 'skinnerve', 'internal/external', 'scars'),
    ('dioica sap', 380, '', 'all', '', 'desert, ice cap, steppe', 'all', 'external', 'scars'),
    ('eghmok moss', 175, 'all', 'all', '', 'boreal forest, deciduous forest', 'head', 'internal', 'wounds'),
    ('genich stem', 275, 'all', 'all', '', 'coastal, freshwater wetland, marine, rainforest', 'torso', 'external', 'scars'),
    ('georin grass', 30, 'all', 'all', '', 'coastal, rural cultivated, savannah', 'neck', 'external', 'wounds'),
    ('hisan flower', None, 'spring, summer, fall', 'day', '', 'freshwater wetland, rural cultivated', 'skinnerve', 'internal/external', 'scars'),
    ('hulij leaves', None, 'all', 'all', '', 'boreal forest, freshwater wetland, rainforest, steppe', 'face', 'internal', 'scars'),
    ('hulnik grass', 100, 'all', 'all', '', 'rural cultivated, savannah, steppe, urban cultivated', 'back', 'external', 'wounds'),
    ('ithor root', None, 'all', 'all', '', 'deciduous forest, highland mountain', 'chest', 'internal', 'wounds'),
    ('jadice flower', 20, 'all', 'all', '', 'badland, desert, rainforest, rural cultivated, urban cultivated', 'limb', 'external', 'wounds'),
    ('jadice pollen', 275, 'all', 'day', '', 'badland, desert, rainforest, rural cultivated, urban cultivated', 'limb', 'external', 'scars'),
    ('junliar stem', 350, 'all', 'all', '', 'boreal forest, chaparral, coastal, deciduous forest, highland mountain', 'back', 'internal', 'wounds'),
    ('lujeakave root', None, 'all', 'all', '', 'rural cultivated, steppe, urban cultivated', 'skinnerve', 'internal/external', 'wounds'),
    ('marram grass', 650, 'all', 'all', '', 'badland, coastal, desert', 'all', 'external', 'wounds'),
    ('marsh woundwort', 750, 'all', 'all', '', 'freshwater wetland, highland mountain', 'all', 'internal/external', 'wounds'),
    ('muljin sap', 175, 'all', 'day', 'higher difficulty in winter', 'freshwater wetland, rural cultivated', 'abdomen', 'internal', 'wounds'),
    ('nemoih root', 60, 'all', 'all', '', 'rural cultivated, steppe, urban cultivated', 'head', 'external', 'wounds'),
    ('nilos grass', 90, 'all', 'all', '', 'boreal forest, chaparral, coastal, deciduous forest', 'abdomen', 'external', 'wounds'),
    ('nuloe stem', 275, 'all', 'all', '', 'boreal forest, chaparral, coastal, deciduous forest', 'limb', 'internal', 'scars'),
    ('ojhenik root', None, 'all', 'day', 'higher difficulty in winter', 'chaparral, coastal, scrub and thorn', 'chest', 'internal', 'scars'),
    ('pink blossom', None, '', '', '', '', '', '', ''),
    ('plovik leaves', 90, 'all', 'all', '', 'boreal forest, freshwater wetland, rainforest, savannah', 'chest', 'external', 'wounds'),
    ('purple blossom', None, '', '', '', '', '', '', ''),
    ('qun pollen', 275, 'all', 'all', '', 'desert, ice cap, steppe', 'face', 'external', 'scars'),
    ('red flower', 50, 'all', 'all', '', '', '', 'external', ''),
    ('riolur leaves', 100, 'spring, summer, fall', 'all', '', 'boreal forest, deciduous forest, steppe', 'neck', 'internal', 'wounds'),
    ('seolarn weed', 70, 'all', 'all', '', '', '', '', ''),
    ('shining clubmoss', 625, 'all', 'all', 'higher difficulty in winter, lower difficulty in fall', 'badland, deciduous forest, freshwater wetland, scrub and thorn', 'all', 'internal/external', 'scars'),
    ('sufil sap', 120, 'all', 'day', '', 'chaparral, coastal, scrub and thorn', 'eye', 'external', 'wounds'),
    ('white blossom', None, '', '', '', '', '', '', ''),
    ('yelith root', 60, 'all', 'all', '', 'chaparral, scrub and thorn, steppe', 'limb', 'internal', 'wounds'),
)

SHOPS = (
    ('aeveaes solution', ('Ain Ghazal Crafting Society Outpost (Ain Ghazal)', "Alchemy Society (Aesry Surlaenis'a)", 'Alchemy Society (Crossing)', 'Alchemy Society (Hibarnhvidar)', "Alchemy Society (Muspar'i)", 'Alchemy Society (Ratha)', 'Alchemy Society (Riverhaven)', 'Alchemy Society (Shard)', 'Alchemy Society (Therenborough)', "Gretzyl the Herbalist's Cottage (Rossman's Landing)", 'Hawst Tarshar (Hibarnhvidar)', 'Langenfirth Crafting Society Outpost (Langenfirth)', 'Leth Deriel Crafting Society Outpost (Leth Deriel)', "M'Riss Crafting Society Outpost (M'Riss)", "Trintah's Herbal Remedies (Mer'Kresh)")),
    ('aloe balm', ()),
    ('ashen flamestalk', ()),
    ('blocil berries', ('Augs Uda (Obsolete) (Siksraja)', "Crin's Herbal Shop (Riverhaven)", "Enescu's Herbs (Fayrin's Rest)", "Mauriga's Botanicals (Crossing)", "Nardel's Dwelling (Blackthorn Canyon)")),
    ('blocil potion', ('Augs Uda (Obsolete) (Siksraja)', "Crin's Herbal Shop (Riverhaven)", "Enescu's Herbs (Fayrin's Rest)", "Mauriga's Botanicals (Crossing)", "Nardel's Dwelling (Blackthorn Canyon)")),
    ('cebi root', ('Augs Uda (Obsolete) (Siksraja), Brother Yorgi', 'Herbalist (Langenfirth)', "Crin's Herbal Shop (Riverhaven)", "Fenwyrthie's Curio Shop (Crossing)", "Green Lady's Glasshouse (Muspar'i)", "Gretzyl the Herbalist's Cottage (Rossman's Landing)", 'Hawst Tarshar (Hibarnhvidar)', "Midwife Neesa's Cottage (Tiger Clan)", "Midwife Neesa's Cottage (obsolete) (Tiger Clan)", "Nardel's Dwelling (Blackthorn Canyon)", "Shard's Osut'vie (Shard)", 'Sisters In Lore (Ratha)', "Taernen's Alchemical and Herbal Supplies (Aesry Surlaenis'a)", "Trintah's Herbal Remedies (Mer'Kresh)")),
    ('eghmok potion', ('Brother Yorgi', 'Herbalist (Langenfirth)', "Crin's Herbal Shop (Riverhaven)", "Gretzyl the Herbalist's Cottage (Rossman's Landing)", 'Hawst Tarshar (Hibarnhvidar)', "Nardel's Dwelling (Blackthorn Canyon)", "Shard's Osut'vie (Shard)", 'Sisters In Lore (Ratha)', "Taernen's Alchemical and Herbal Supplies (Aesry Surlaenis'a)", "Tobriash's Workshop (Muspar'i)", "Trintah's Herbal Remedies (Mer'Kresh)")),
    ('genich stem', ('Ain Ghazal Crafting Society Outpost (Ain Ghazal)', "Alchemy Society (Aesry Surlaenis'a)", 'Alchemy Society (Crossing)', 'Alchemy Society (Hibarnhvidar)', "Alchemy Society (Muspar'i)", 'Alchemy Society (Ratha)', 'Alchemy Society (Riverhaven)', 'Alchemy Society (Shard)', 'Alchemy Society (Therenborough) (Therenborough), Brother Yorgi', 'Herbalist (Langenfirth)', 'Hawst Tarshar (Hibarnhvidar)', 'Langenfirth Crafting Society Outpost (Langenfirth)', 'Leth Deriel Crafting Society Outpost (Leth Deriel)', "M'Riss Crafting Society Outpost (M'Riss)", "Midwife Neesa's Cottage (Tiger Clan)... further results")),
    ('georin salve', ('Ain Ghazal Crafting Society Outpost (Ain Ghazal)', "Alchemy Society (Aesry Surlaenis'a)", 'Alchemy Society (Crossing)', 'Alchemy Society (Hibarnhvidar)', "Alchemy Society (Muspar'i)", 'Alchemy Society (Ratha)', 'Alchemy Society (Riverhaven)', 'Alchemy Society (Shard)', 'Alchemy Society (Therenborough) (Therenborough), Brother Yorgi', 'Herbalist (Langenfirth)', "Crin's Herbal Shop (Riverhaven)", "Enescu's Herbs (Fayrin's Rest)", "Gretzyl the Herbalist's Cottage (Rossman's Landing)", 'Hawst Tarshar (Hibarnhvidar)', 'Langenfirth Crafting Society Outpost (Langenfirth)... further results')),
    ('hisan salve', ('Augs Uda (Obsolete) (Siksraja), Brother Yorgi', 'Herbalist (Langenfirth)', "Crin's Herbal Shop (Riverhaven)", "Fenwyrthie's Curio Shop (Crossing)", "Gretzyl the Herbalist's Cottage (Rossman's Landing)", 'Hawst Tarshar (Hibarnhvidar)', "Midwife Neesa's Cottage (Tiger Clan)", "Midwife Neesa's Cottage (obsolete) (Tiger Clan)", "Nardel's Dwelling (Blackthorn Canyon)", "Shard's Osut'vie (Shard)", 'Sisters In Lore (Ratha)', "Taernen's Alchemical and Herbal Supplies (Aesry Surlaenis'a)", "Tobriash's Workshop (Muspar'i)", "Trintah's Herbal Remedies (Mer'Kresh)")),
    ('hulij elixir', ('Augs Uda (Obsolete) (Siksraja), Brother Yorgi', 'Herbalist (Langenfirth)', 'Hawst Tarshar (Hibarnhvidar)', "Midwife Neesa's Cottage (Tiger Clan)", "Midwife Neesa's Cottage (obsolete) (Tiger Clan)", "Shard's Osut'vie (Shard)", 'Sisters In Lore (Ratha)', "Taernen's Alchemical and Herbal Supplies (Aesry Surlaenis'a)", "Trintah's Herbal Remedies (Mer'Kresh)")),
    ('hulnik grass', ('Augs Uda (Obsolete) (Siksraja), Brother Yorgi', 'Herbalist (Langenfirth)', "Crin's Herbal Shop (Riverhaven)", "Enescu's Herbs (Fayrin's Rest)", "Green Lady's Glasshouse (Muspar'i)", "Gretzyl the Herbalist's Cottage (Rossman's Landing)", 'Hawst Tarshar (Hibarnhvidar)', "Mauriga's Botanicals (Crossing)", "Nardel's Dwelling (Blackthorn Canyon)", "Shard's Osut'vie (Shard)", 'Sisters In Lore (Ratha)', "Taernen's Alchemical and Herbal Supplies (Aesry Surlaenis'a)", "Trintah's Herbal Remedies (Mer'Kresh)")),
    ('ithor potion', ('Ain Ghazal Crafting Society Outpost (Ain Ghazal)', "Alchemy Society (Aesry Surlaenis'a)", 'Alchemy Society (Crossing)', 'Alchemy Society (Hibarnhvidar)', "Alchemy Society (Muspar'i)", 'Alchemy Society (Ratha)', 'Alchemy Society (Riverhaven)', 'Alchemy Society (Shard)', 'Alchemy Society (Therenborough)', 'Augs Uda (Obsolete) (Siksraja), Brother Yorgi', 'Herbalist (Langenfirth)', "Crin's Herbal Shop (Riverhaven)", "Enescu's Herbs (Fayrin's Rest)", "Gretzyl the Herbalist's Cottage (Rossman's Landing)", 'Hawst Tarshar (Hibarnhvidar)... further results')),
    ('jadice flower', ('Ain Ghazal Crafting Society Outpost (Ain Ghazal)', "Alchemy Society (Aesry Surlaenis'a)", 'Alchemy Society (Crossing)', 'Alchemy Society (Hibarnhvidar)', "Alchemy Society (Muspar'i)", 'Alchemy Society (Ratha)', 'Alchemy Society (Riverhaven)', 'Alchemy Society (Shard)', 'Alchemy Society (Therenborough)', 'Augs Uda (Obsolete) (Siksraja), Brother Yorgi', 'Herbalist (Langenfirth)', "Crin's Herbal Shop (Riverhaven)", "Enescu's Herbs (Fayrin's Rest)", "Green Lady's Glasshouse (Muspar'i)", "Gretzyl the Herbalist's Cottage (Rossman's Landing)... further results")),
    ('junliar stem', ('Ain Ghazal Crafting Society Outpost (Ain Ghazal)', "Alchemy Society (Aesry Surlaenis'a)", 'Alchemy Society (Crossing)', 'Alchemy Society (Hibarnhvidar)', "Alchemy Society (Muspar'i)", 'Alchemy Society (Ratha)', 'Alchemy Society (Riverhaven)', 'Alchemy Society (Shard)', 'Alchemy Society (Therenborough)', 'Augs Uda (Obsolete) (Siksraja), Brother Yorgi', 'Herbalist (Langenfirth)', "Crin's Herbal Shop (Riverhaven)", "Enescu's Herbs (Fayrin's Rest)", "Green Lady's Glasshouse (Muspar'i)", "Gretzyl the Herbalist's Cottage (Rossman's Landing)... further results")),
    ('lujeakave elixir', ("Gretzyl the Herbalist's Cottage (Rossman's Landing)", 'Hawst Tarshar (Hibarnhvidar)', "Trintah's Herbal Remedies (Mer'Kresh)")),
    ('marram grass', ()),
    ('marsh woundwort', ()),
    ('muljin sap', ('Augs Uda (Obsolete) (Siksraja), Brother Yorgi', 'Herbalist (Langenfirth)', "Crin's Herbal Shop (Riverhaven)", "Enescu's Herbs (Fayrin's Rest)", "Green Lady's Glasshouse (Muspar'i)", "Gretzyl the Herbalist's Cottage (Rossman's Landing)", 'Hawst Tarshar (Hibarnhvidar)', "Mauriga's Botanicals (Crossing)", "Nardel's Dwelling (Blackthorn Canyon)", "Shard's Osut'vie (Shard)", 'Sisters In Lore (Ratha)', "Taernen's Alchemical and Herbal Supplies (Aesry Surlaenis'a)", "Trintah's Herbal Remedies (Mer'Kresh)")),
    ('nemoih root', ('Ain Ghazal Crafting Society Outpost (Ain Ghazal)', "Alchemy Society (Aesry Surlaenis'a)", 'Alchemy Society (Crossing)', 'Alchemy Society (Hibarnhvidar)', "Alchemy Society (Muspar'i)", 'Alchemy Society (Ratha)', 'Alchemy Society (Riverhaven)', 'Alchemy Society (Shard)', 'Alchemy Society (Therenborough)', 'Augs Uda (Obsolete) (Siksraja), Brother Yorgi', 'Herbalist (Langenfirth)', "Crin's Herbal Shop (Riverhaven)", "Enescu's Herbs (Fayrin's Rest)", "Green Lady's Glasshouse (Muspar'i)", "Gretzyl the Herbalist's Cottage (Rossman's Landing)... further results")),
    ('nilos salve', ('Ain Ghazal Crafting Society Outpost (Ain Ghazal)', "Alchemy Society (Aesry Surlaenis'a)", 'Alchemy Society (Crossing)', 'Alchemy Society (Hibarnhvidar)', "Alchemy Society (Muspar'i)", 'Alchemy Society (Ratha)', 'Alchemy Society (Riverhaven)', 'Alchemy Society (Shard)', 'Alchemy Society (Therenborough)', 'Augs Uda (Obsolete) (Siksraja), Brother Yorgi', 'Herbalist (Langenfirth)', "Crin's Herbal Shop (Riverhaven)", "Enescu's Herbs (Fayrin's Rest)", "Gretzyl the Herbalist's Cottage (Rossman's Landing)", 'Hawst Tarshar (Hibarnhvidar)... further results')),
    ('nuloe stem', ('Brother Yorgi', 'Herbalist (Langenfirth)', "Midwife Neesa's Cottage (Tiger Clan)", "Midwife Neesa's Cottage (obsolete) (Tiger Clan)", "Shard's Osut'vie (Shard)", 'Sisters In Lore (Ratha)', "Taernen's Alchemical and Herbal Supplies (Aesry Surlaenis'a)")),
    ('ojhenik potion', ('Ain Ghazal Crafting Society Outpost (Ain Ghazal)', "Alchemy Society (Aesry Surlaenis'a)", 'Alchemy Society (Crossing)', 'Alchemy Society (Hibarnhvidar)', "Alchemy Society (Muspar'i)", 'Alchemy Society (Ratha)', 'Alchemy Society (Riverhaven)', 'Alchemy Society (Shard)', 'Alchemy Society (Therenborough) (Therenborough), Brother Yorgi', 'Herbalist (Langenfirth)', 'Hawst Tarshar (Hibarnhvidar)', 'Langenfirth Crafting Society Outpost (Langenfirth)', 'Leth Deriel Crafting Society Outpost (Leth Deriel)', "M'Riss Crafting Society Outpost (M'Riss)", "Midwife Neesa's Cottage (Tiger Clan)... further results")),
    ('plovik leaves', ('Ain Ghazal Crafting Society Outpost (Ain Ghazal)', "Alchemy Society (Aesry Surlaenis'a)", 'Alchemy Society (Crossing)', 'Alchemy Society (Hibarnhvidar)', "Alchemy Society (Muspar'i)", 'Alchemy Society (Ratha)', 'Alchemy Society (Riverhaven)', 'Alchemy Society (Shard)', 'Alchemy Society (Therenborough)', 'Augs Uda (Obsolete) (Siksraja), Brother Yorgi', 'Herbalist (Langenfirth)', "Crin's Herbal Shop (Riverhaven)", "Enescu's Herbs (Fayrin's Rest)", "Green Lady's Glasshouse (Muspar'i)", "Gretzyl the Herbalist's Cottage (Rossman's Landing)... further results")),
    ('qun pollen', ('Ain Ghazal Crafting Society Outpost (Ain Ghazal)', "Alchemy Society (Aesry Surlaenis'a)", 'Alchemy Society (Crossing)', 'Alchemy Society (Hibarnhvidar)', "Alchemy Society (Muspar'i)", 'Alchemy Society (Ratha)', 'Alchemy Society (Riverhaven)', 'Alchemy Society (Shard)', 'Alchemy Society (Therenborough)', 'Augs Uda (Obsolete) (Siksraja), Brother Yorgi', 'Herbalist (Langenfirth)', 'Hawst Tarshar (Hibarnhvidar)', 'Langenfirth Crafting Society Outpost (Langenfirth)', 'Leth Deriel Crafting Society Outpost (Leth Deriel)', "M'Riss Crafting Society Outpost (M'Riss)... further results")),
    ('riolur leaves', ('Ain Ghazal Crafting Society Outpost (Ain Ghazal)', "Alchemy Society (Aesry Surlaenis'a)", 'Alchemy Society (Crossing)', 'Alchemy Society (Hibarnhvidar)', "Alchemy Society (Muspar'i)", 'Alchemy Society (Ratha)', 'Alchemy Society (Riverhaven)', 'Alchemy Society (Shard)', 'Alchemy Society (Therenborough)', 'Augs Uda (Obsolete) (Siksraja), Brother Yorgi', 'Herbalist (Langenfirth)', "Crin's Herbal Shop (Riverhaven)", "Enescu's Herbs (Fayrin's Rest)", "Green Lady's Glasshouse (Muspar'i)", "Gretzyl the Herbalist's Cottage (Rossman's Landing)... further results")),
    ('shining clubmoss', ()),
    ('sufil sap', ('Augs Uda (Obsolete) (Siksraja), Brother Yorgi', 'Herbalist (Langenfirth)', "Crin's Herbal Shop (Riverhaven)", "Enescu's Herbs (Fayrin's Rest)", "Green Lady's Glasshouse (Muspar'i)", "Gretzyl the Herbalist's Cottage (Rossman's Landing)", 'Hawst Tarshar (Hibarnhvidar)', "Mauriga's Botanicals (Crossing)", "Nardel's Dwelling (Blackthorn Canyon)", "Shard's Osut'vie (Shard)", 'Sisters In Lore (Ratha)', "Taernen's Alchemical and Herbal Supplies (Aesry Surlaenis'a)", "Trintah's Herbal Remedies (Mer'Kresh)")),
    ('yelith root', ('Augs Uda (Obsolete) (Siksraja), Brother Yorgi', 'Herbalist (Langenfirth)', "Crin's Herbal Shop (Riverhaven)", "Enescu's Herbs (Fayrin's Rest)", "Green Lady's Glasshouse (Muspar'i)", "Gretzyl the Herbalist's Cottage (Rossman's Landing)", 'Hawst Tarshar (Hibarnhvidar)', "Mauriga's Botanicals (Crossing)", "Nardel's Dwelling (Blackthorn Canyon)", "Shard's Osut'vie (Shard)", 'Sisters In Lore (Ratha)', "Taernen's Alchemical and Herbal Supplies (Aesry Surlaenis'a)", "Trintah's Herbal Remedies (Mer'Kresh)")),
)
# fmt: on
